### ISSUE TITLE
Magic Constant: 0.8

### ISSUE THREAD

**Issue by coursar** [aksiaaksi/HW1_distance_remaining_on_fuel#1]
Что за магическое число 0.8? Нужно вынести в переменную и дать имя, которое бы давало понять, что это за значение

https://github.com/aksiaaksi/HW1_distance_remaining_on_fuel/blob/ac19be05908479d27fb0ea10251798501d65d31a/distance_remaining_fuel.py#L12

**Comment by aksiaaksi** [comment]
см #1 
исправлено в 318202af2f4e017fddc5dc3572191edebbf240ab

**Comment by coursar** [comment]
Закрывайте таски сообщениями коммиттов
